In [31]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Bagian Baru

In [32]:
cs_dataset = pd.read_csv('sample_data/Customertravel.csv')

In [33]:
cs_dataset.head()

Age  FrequentFlyer  AnnualIncomeClass  ServicesOpted  \
0   34              0                  2              6   
1   34              1                  1              5   
2   37              0                  2              3   
3   30              0                  2              2   
4   30              0                  1              1   

   AccountSyncedToSocialMedia  BookedHotelOr0t  Target  
0                           0                1       0  
1                           1                0       1  
2                           1                0       0  
3                           0                0       0  
4                           0                0       0

In [34]:
cs_dataset.shape

(954, 7)

In [35]:
# memisahkan data dan label

x = cs_dataset.drop (columns='Target', axis=1)
y = cs_dataset['Target']

In [36]:
print(x)

     Age  FrequentFlyer  AnnualIncomeClass  ServicesOpted  \
0     34              0                  2              6   
1     34              1                  1              5   
2     37              0                  2              3   
3     30              0                  2              2   
4     30              0                  1              1   
..   ...            ...                ...            ...   
949   31              1                  1              1   
950   30              0                  2              5   
951   37              0                  2              4   
952   30              0                  1              1   
953   31              1                  3              1   

     AccountSyncedToSocialMedia  BookedHotelOr0t  
0                             0                1  
1                             1                0  
2                             1                0  
3                             0                0  
4           

In [37]:
print(y)

0      0
1      1
2      0
3      0
4      0
      ..
949    0
950    0
951    0
952    0
953    0
Name: Target, Length: 954, dtype: int64


In [38]:
# standarisasi data

scaler = StandardScaler() 

In [39]:
scaler.fit(x)

StandardScaler()

In [40]:
standar_data = scaler.transform(x)

In [41]:
print(standar_data)

[[ 0.56690365 -0.65432692  0.33167822  2.21932995 -0.77849894  1.2344268 ]
 [ 0.56690365  1.52828804 -1.06224698  1.59642887  1.28452326 -0.81009259]
 [ 1.46628183 -0.65432692  0.33167822  0.35062671  1.28452326 -0.81009259]
 ...
 [ 1.46628183 -0.65432692  0.33167822  0.97352779 -0.77849894 -0.81009259]
 [-0.63226726 -0.65432692 -1.06224698 -0.89517545  1.28452326  1.2344268 ]
 [-0.33247453  1.52828804  1.72560341 -0.89517545 -0.77849894 -0.81009259]]


In [42]:
x = standar_data
y = cs_dataset['Target']

In [43]:
print(x)
print(y)

[[ 0.56690365 -0.65432692  0.33167822  2.21932995 -0.77849894  1.2344268 ]
 [ 0.56690365  1.52828804 -1.06224698  1.59642887  1.28452326 -0.81009259]
 [ 1.46628183 -0.65432692  0.33167822  0.35062671  1.28452326 -0.81009259]
 ...
 [ 1.46628183 -0.65432692  0.33167822  0.97352779 -0.77849894 -0.81009259]
 [-0.63226726 -0.65432692 -1.06224698 -0.89517545  1.28452326  1.2344268 ]
 [-0.33247453  1.52828804  1.72560341 -0.89517545 -0.77849894 -0.81009259]]
0      0
1      1
2      0
3      0
4      0
      ..
949    0
950    0
951    0
952    0
953    0
Name: Target, Length: 954, dtype: int64


In [45]:
# memisahkan data training dan data testing

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size= 0.2, stratify=y, random_state=2)

In [46]:
print(x.shape, X_train.shape, X_test.shape) 

(954, 6) (763, 6) (191, 6)


In [47]:
# membuat data latih menggunakan algoritma SVM

classifier = svm.SVC(kernel='linear')

In [48]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [49]:
#membuat evaluasi untuk mengukur tingkat akurasi

X_train_predic = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_predic, Y_train)

In [50]:
print('Akurasi data training adalah = ', training_data_accuracy)

Akurasi data training adalah =  0.8191349934469201


In [51]:
X_test_predic = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_predic, Y_test)

In [52]:
print('Akurasi data testing adalah = ', test_data_accuracy)

Akurasi data testing adalah =  0.8272251308900523


In [53]:
# membuat model prediksi

input_data = (32, 3, 2, 3, 4, 1)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

predic = classifier.predict(std_data)
print(predic)

if (predic[0] == 0):
    print('loyal ')
else :
    print('churn')

[[-0.03268181  5.89351795  0.33167822  0.35062671  7.47358986  1.2344268 ]]
[1]
churn


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [54]:
# simpan model

import pickle

In [55]:
filename = 'customertravel1.sav'
pickle.dump(classifier, open(filename,'wb'))